language: C++
os: osx


before_install:
  - brew update
  - brew tap homebrew/science
  - brew install Caskroom/cask/xquartz
  - brew install r
  - Rscript -e "install.packages('devtools')"
  - Rscript -e "devtools::install_github('appelmar/dtwSat')"