language: r

r:
  - release
  - devel

deploy.skip_cleanup: true

sudo: required
dist: trusty
cache:
  - packages
  - ccache
latex: true

r_github_packages:
  - r-lib/covr
  
bioc_packages:
  - Biobase

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - libgdal-dev

before_install:
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'
  - R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

after_success:
  - R -q -e 'covr::codecov(quiet = FALSE)'
  
install: R -q -e 'tic::install()'
script: R -q -e 'tic::script()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
   provider: script
   script: R -q -e 'tic::deploy()'
   on:
     branch: master
